#File roles/deploy/tasks/tag-instances.yml
- name: tag ec2 instance
  local_action: ec2_tag resource={{ item.id }} region={{ aws_region }} state=present
  args:
    tags:
      Name: "{{ ec2_tags }}"
  with_items: "{{ ec2.instances }}"
  when: node_count == 1
  tags:
    - tag

- name: create identifier sequence id for tag ec2 instances
  debug: msg="{{ item }}"
  with_sequence: start="{{ start_index }}" count="{{ node_count }}" format=%02d
  register: sequence
  when: node_count > 1

- name: tag multiple ec2 instances sequentially
  local_action: ec2_tag resource={{ item.0.id }} region={{ aws_region }} state=present
  args:
    tags:
     Name: "{{ ec2_tags }} {{ item.1.msg }}"
     Region: "{{ aws_region }}"
  with_together:
    - "{{ ec2.instances }}"
    - "{{ sequence.results }}"
  when: node_count > 1
  tags:
    - tag
