#File playbooks/install-jenkins-slave.yml

- name: Actions for both Jenkins master and slaves
  hosts: jenkins-slave
  vars_files:
  - /etc/ansible/vault/vault.yml
  roles:
    - install-jenkins-slave
